# Generated by Django 5.2.6 on 2025-10-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='url_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
