# Generated by Django 5.2.6 on 2025-12-13 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyresearchmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('birth', 'Birth'), ('baptism', 'Baptism'), ('christening', 'Christening'), ('death', 'Death'), ('burial', 'Burial'), ('marriage', 'Marriage'), ('divorce', 'Divorce'), ('immigration', 'Immigration'), ('emigration', 'Emigration'), ('census', 'Census'), ('residence', 'Residence'), ('occupation', 'Occupation'), ('military', 'Military Service'), ('education', 'Education')], max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='familyresearchmanager.person')),
            ],
        ),
    ]
