# Generated by Django 5.2.6 on 2025-12-14 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyresearchmanager', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('repo_type', models.CharField(choices=[('archive', 'Archive/Library'), ('courthouse', 'Courthouse'), ('church', 'Church/Religious'), ('website', 'Website/Database'), ('personal', 'Personal Collection')], max_length=50)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('item_identifier', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(blank=True, max_length=50)),
                ('line_number', models.CharField(blank=True, max_length=50)),
                ('name_as_recorded', models.CharField(blank=True, max_length=255)),
                ('transcription', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='familyresearchmanager.event')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='familyresearchmanager.source')),
            ],
        ),
        migrations.CreateModel(
            name='SourceAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_points', to='familyresearchmanager.repository')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='familyresearchmanager.source')),
            ],
        ),
        migrations.CreateModel(
            name='SourceCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('publication_info', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_creators', to='familyresearchmanager.repository')),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='source_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='familyresearchmanager.sourcecreator'),
        ),
    ]
