# Generated by Django 5.2.6 on 2025-12-14 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyresearchmanager', '0003_repository_source_citation_sourceaccess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='sources/'),
        ),
        migrations.AddField(
            model_name='source',
            name='page_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sourceaccess',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='research_log/'),
        ),
        migrations.AddField(
            model_name='sourceaccess',
            name='line_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sourceaccess',
            name='person_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sourceaccess',
            name='access_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
