# Generated by Django 5.2.6 on 2025-12-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyresearchmanager', '0004_source_file_source_page_number_source_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='event',
        ),
        migrations.AddField(
            model_name='citation',
            name='event',
            field=models.ManyToManyField(related_name='citations', to='familyresearchmanager.event'),
        ),
    ]
