# Generated by Django 5.2.6 on 2025-11-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_following_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
